language: c

services:
  - docker

before_install:
  - docker build -t wobbals/ptsknife .

script:
- echo "skipping tests"

deploy:
  provider: script
  script: bash bin/docker_push
  on:
    branch: master
